=== Shre0710/WTL/ASSIGNMENT NO.5/DTD/library.dtd
<!ELEMENT library (book+)>
<!ELEMENT book (title, author, genre, year, price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== Shre0710/WTL/ASSIGNMENT NO.5/DTD/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="library.xsl"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library>
    <book>
        <title>Introduction to Algorithms</title>
        <author>Thomas H. Cormen</author>
        <genre>Computer Science</genre>
        <year>2009</year>
        <price>45.99</price>
    </book>
    <book>
        <title>Clean Code</title>
        <author>Robert C. Martin</author>
        <genre>Software Development</genre>
        <year>2008</year>
        <price>39.99</price>
    </book>
    <book>
        <title>The Pragmatic Programmer</title>
        <author>Andrew Hunt</author>
        <genre>Programming</genre>
        <year>1999</year>
        <price>42.50</price>
    </book>
</library>
